### ISSUE TITLE
Performance improvement: use Array.prototype.push.apply instead of concat

### ISSUE THREAD

**Issue by triccardi-systran** [archiverjs/archiver-utils#1]
https://github.com/archiverjs/archiver-utils/blob/90027dab81b92b4b420e45761da46160f56534a2/index.js#L145

```javascript
// current version
results = results.concat(res);
// faster version
Array.prototype.push.apply(results, res);
````

See https://jsperf.com/javascript-array-concat-vs-push/100 for a benchmark.

**Comment by ctalkington** [comment]
im guessing since node uses v8 the perf bonus would carry across? has this made a major difference in any of your own tests?

**Comment by triccardi-systran** [comment]
Yes I assumed that it would also benefit on nodejs.
I saw this patch on another project (mongodb/node-mongodb-native@cd6f06b7d08f0b4750c5d4986899a6b81d2b28f6) during my evaluation of the `archiver` module.
I haven't done any test, so it's indeed purely theoretical, but I think this may have an impact with a large number of files, which is a valid use-case.
And I don't see any downside.
