### ISSUE TITLE
Buffer() is deprecated

### ISSUE THREAD

**Issue by squio** [archiverjs/archiver-utils#128]
When running the parent `archiver` utility the following warning is printed to the console:

```
[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. 
Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. 
```

The warning is about the calls `new Buffer(...)` in this package.
These should be replaced by `Buffer.alloc(number)` and `Buffer.from(string)` instead

**Comment by squio** [comment]
While preparing a PR I find that the current v 3.0.0 already fixes this but somehow the `archiver`'s  `package.json` still references an old version `2.1.0` - creating an issue there as well

**Comment by jsking216** [comment]
this is a pretty annoying problem as it causes error level messages to be thrown in node 18 lambdas

if it will not be addressed, I will need to move to a different library. is this utility dead?

**Comment by ctalkington** [comment]
v3.0.3 published
