### ISSUE TITLE
Veracode security issue for glob@7.2.3 -> inflight@1.0.6

### ISSUE THREAD

**Issue by crowmw** [archiverjs/archiver-utils#168]
archiver-utils@4.0.1 depends on glob@7.2.3 package which also has a vulnerable dependency 'inflight@1.0.6'.
As per 'https://github.com/isaacs/inflight/issues/18' vulnerable dependency is being fixed in glob@9.0.0.

✅ What did you expect to see?
Cucumber lib using an updated version of glob. > 9.0.0 without any vulnerabilities

📦 Which tool/library version are you using?
4.0.1

🔬 How could we reproduce it?

Install archiver-utils@4.0.1
npm ls inflight
Observe that archiver-utils is dependent is glob@7.2.3 -> inflight@1.0.6

**Comment by raffaele-moodys** [comment]
+1

**Comment by mysteron** [comment]
+1

**Comment by mysteron** [comment]
+1

**Comment by sumitaka-ueda-rv** [comment]
+1

**Comment by arizmendiomar** [comment]
Any news about this issue?
