### ISSUE TITLE
Consider switching from specialized lodash modules to lodash

### ISSUE THREAD

**Issue by std4lqi** [archiverjs/archiver-utils#40]
The latest lodash.defaults on npmjs is 4.2.0 at https://www.npmjs.com/package/lodash.defaults, which was published about 4 years ago. 

There are a couple of vulnerabilities relevant to lodash.defaults@4.2.0 at

https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Alodash&cpe_product=cpe%3A%2F%3Alodash%3Alodash&cpe_version=cpe%3A%2F%3Alodash%3Alodash%3A4.2.0

Please consider to depend on lodash, instead of the specialized ones that are out of publish actually.

**Comment by ctalkington** [comment]
this should be refactor in the next few days

**Comment by std4lqi** [comment]
Thanks, @ctalkington !
