### ISSUE TITLE
Maximum call stack size exceeded when calling walkdir

### ISSUE THREAD

**Issue by rloehr** [archiverjs/archiver-utils#5]
The walkdir method is susceptible to maximum call stack sized exceeded errors.

Calling walkdir on my root directory as follows:

var  utils = require('archiver-utils');

utils.walkdir('/', function(err, data) {
	console.log('done');
})

Results in:

536379   //this count is the number of times next() was called

/Users/loehrm1/code/rueltest/node_modules/archiver-utils/index.js:149
            Array.prototype.push.apply(results, res);
                                 ^
RangeError: Maximum call stack size exceeded
    at /Users/loehrm1/code/rueltest/node_modules/archiver-utils/index.js:149:34
    at next (/Users/loehrm1/code/rueltest/node_modules/archiver-utils/index.js:134:16)
    at /Users/loehrm1/code/rueltest/node_modules/archiver-utils/index.js:151:13
    at next (/Users/loehrm1/code/rueltest/node_modules/archiver-utils/index.js:134:16)
    at /Users/loehrm1/code/rueltest/node_modules/archiver-utils/index.js:155:11
    at Object.oncomplete (fs.js:108:15)

**Comment by bdmayes** [comment]
Seeing the same behavior here. The problem appears to stem from the usage of apply()'ing to the push prototype. It seems this change was done to try and squeeze out the maximum amount of performance:

https://github.com/archiverjs/archiver-utils/issues/1

However, calling apply() with a large array as the second argument is prone to failure, as documented here:

http://stackoverflow.com/questions/1374126/how-to-extend-an-existing-javascript-array-with-another-array-without-creating/17368101#17368101


I can pretty easily recreate this against an xcode directory on my Mac. I modified the code slightly to log the directory it was walking as well as the length of res, assuming res is an array. It fails on a directory with 185,585 files in it:

```
$ cd /tmp
$ npm install archiver-utils
$ cat test.js
var utils = require('archiver-utils');
utils.walkdir('/Applications/Xcode.app', function(err, data) {
  console.log('done');
});
$ tail -n 20 node_modules/archiver-utils/index.js
          relative: path.relative(base, filepath).replace(/\\/g, '/'),
          stats: stats
        });

        if (stats && stats.isDirectory()) {
          utils.walkdir(filepath, base, function(err, res) {
            // added these lines
            console.log('Recursively walking ' + filepath);
            if (res instanceof Array) {
              console.log('res.length: ' + res.length);
            }
            // end of my additions
            Array.prototype.push.apply(results, res);
            next();
          });
        } else {
          next();
        }
      });
    })();
  });
};
$ node test.js  // runs for a few seconds and then...

Recursively walking /Applications/Xcode.app/Contents/Developer/Documentation/DocSets
res.length: 185585

/private/tmp/node_modules/archiver-utils/index.js:149
            Array.prototype.push.apply(results, res);
                                 ^
RangeError: Maximum call stack size exceeded
```

As suggested, you should be using a loop-based technique to push into the array to avoid this. You could set a threshold to determine when to use apply (for performance) and when to use a loop (to avoid exceeding the stack), but as noted this threshold differs by browser, and perhaps platform, and so on. Thus, it's probably safest to avoid apply() entirely and just iterate, regardless of the length. I was able to get it to successfully process this large directory by modifying the walkdir function to use the following logic for processing directories:

```
if (stats && stats.isDirectory()) {
  utils.walkdir(filepath, base, function(err, res) {
    if (res instanceof Array) {
      res.forEach(function(singleRes) {
        results.push(singleRes);
      });
    }
    next();
  });
} else {
  next();
}
```

**Comment by bdmayes** [comment]
Ok, the following (simpler) logic seems to be working fine. My teammate is forking this repo and will open a PR against it to include this:

```
if (stats && stats.isDirectory()) {
  utils.walkdir(filepath, base, function(err, res) {
    res.forEach(function(singleResult) {
      results.push(singleResult);
    });
    next();
  });
} else {
  next();
}
```

**Comment by ctalkington** [comment]
commited will be in upcoming release if all testing goes well.
